[project]
name = "graph-neural-nets"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.17.0",
    "matplotlib>=3.10.7",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "tabulate>=0.9.0",
    "torch>=2.9.0",
    "torch-geometric>=2.7.0",
]
